#ifndef QAS_H
#define QAS_H

#include "qas_enum_types.h"

#ifndef QT_AUTO_SERIALIZATION_COMPILER_RUN

#define QAS_ATTRIBUTE(ATTR)

#define QAS_IGNORE

#define QAS_JSON_DECLARE(TYPE) QAS_JSON_DECLARE_IMPL(TYPE)

#define QAS_ENUM_DECLARE(TYPE) QAS_ENUM_DECLARE_IMPL(TYPE)

#else
#define QAS_ATTRIBUTE(ATTR) QAS_ATTRIBUTE(ATTR)
#define QAS_IGNORE QAS_IGNORE
#define QAS_JSON_DECLARE(TYPE) QAS_JSON_DECLARE(TYPE)
#define QAS_ENUM_DECLARE(TYPE) QAS_ENUM_DECLARE(TYPE)
#endif


#endif // QAS_H
